name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fallen:
    runs-on: self-hosted
    steps:
      - name: say hello
        run: echo "Hello world!"

  build:
    runs-on: self-hosted
      env:
        working-directory: ./.github/workflows
    steps:
      - name: using Makefile
        run: bash make.sh
