name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fallen:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello world!"
