name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fallen:
    runs-on: self-hosted
    steps:
      - name: say hello
        run: echo "Hello world!"

  build:
    runs-on: self-hosted
    steps:
      - name: using Makefile
        run: out=$(ls -lah && pwd); echo "$out"
